const MORALIS_API_KEY = process.env.MORALIS_API_KEY;
const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS;
// const BSC_TESTNET_CHAINID = process.env.BSC_TESTNET_CHAINID;
const BSC_TESTNET_CHAINID_HEX = process.env.BSC_TESTNET_CHAINID_HEX;
